---
title: "Untitled"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
resource_files:
- data/dd.rda
- data-raw/dd.csv
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```


```{r}
##readr::write_csv(alharbi::dd,'data-raw/dd.csv')
dd <- readr::read_csv('data-raw/dd.csv')

```
```{r}
##readr::write_rds(alharbi::country_choices,'data-raw/country_choices.rds')
country_choices <- readr::read_rds('data-raw/country_choices.rds')
```


```{r}
outcomes <- c("SH.UHC.NOP2.ZG", 
                    "SH.XPD.CHEX.PP.CD" ,
                    "SH.XPD.EHEX.PP.CD",
                    "SH.XPD.OOPC.CH.ZS")
```


```{r}
predicters <- c("NY.ADJ.NNTY.KD.ZG" ,
                    "SP.DYN.LE00.IN" ,
                    "SH.XPD.PVTD.PP.CD",
                    "SH.XPD.GHED.PP.CD")
```

Inputs {.sidebar}
-----------------------------------------

```{r, include=TRUE}
# shiny inputs defined here
selectInput(
  "country",
  label = "select country",
  choices = country_choices,
  selected = c("Saudi Arabia", "United States", "United Kingdom" ),
  multiple = TRUE,
  selectize = TRUE,
  width = NULL,
  size = NULL
)

```

```{r, include=TRUE}
sliderInput("year", label = h3("year"), min = 1960, 
        max = 2020, value = c(2020, 1960))

```





```{r, include=TRUE}
# shiny inputs defined here
selectInput(
  "outcome",
  label = "select an outcome",
  choices = outcomes,
  selected = outcomes[2],
  multiple = FALSE,
  selectize = TRUE,
  width = NULL,
  size = NULL
)
```


```{r, include=TRUE}
# shiny inputs defined here
selectInput(
  "predicter",
  label = "select a predicter",
  choices = predicters,
  selected = predicters[1],
  multiple = FALSE,
  selectize = TRUE,
  width = NULL,
  size = NULL
)
```


Column {.tabset}
-----------------------------------------------------------------------

### Chart A


```{r, include=TRUE}
renderPlot({
  dd %>% 
    filter(country %in% input$country) %>% 
    filter(between(year,input$year[[1]], input$year[[2]])) %>% 
  select( year, country, input$outcome,input$predicter) %>% 
  na.omit() %>% 
  ggplot(aes(x=year, y=!!sym(input$predicter)
, color= country)) +
    geom_smooth() +
  geom_point()
})
```

### Chart B

```{r, include=TRUE}
#renderPrint(input$year)
renderPlot({
  dd %>% 
    filter(country %in% input$country) %>% 
    filter(between(year,input$year[[1]], input$year[[2]])) %>% 
  select( year, country, input$outcome,input$predicter) %>% 
  na.omit() %>% 
  ggplot(aes(x=!!sym(input$predicter), y=!!sym(input$outcome)
, color= country)) +
    geom_smooth() +
  geom_point()
})
```


### Chart C

```{r, include=TRUE}
renderPlot({
  dd %>% 
    filter(country %in% input$country) %>% 
    filter(between(year,input$year[[1]], input$year[[2]])) %>% 
  select( year, country, input$outcome,input$predicter) %>% 
  na.omit() %>% 
  ggplot(aes(x=year, y=!!sym(input$outcome), color= country)) +
  geom_point()+
  guides(color = FALSE)
})
```

### Chart D

```{r, include=TRUE}
renderPrint({
  formula1 <- rlang::new_formula(sym(input$outcome), sym(input$predicter))
  #formula1
linearMod <- lm(formula1, data=dd)
summary(linearMod)
})
```



