---
title: "The Reationship between Health Insurance on Government Policy."
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## To do list (Stories)

1. Find the data series. (October 15)
   * 10 series with good data coverage
2. Design the plots and data explorations. (October 22)
   * Make 5 plots to be generalized into Shiny.
3. Create R shiny interface to the data. (October 29)
4. Create R shiny users interface.(November 5)
5. Write the R shiny server cod.(November 12)
6. Deploy the R shiny app.(November 20)

## Utility of the app

The user will be able to select from 10 to 20 curated series that are populated, 
and are relevant to the topic of Health Insurance.

The user will be able to index by year and country an data series.

There will be a selection of graphical analysis provided by RShiny.

There will be a selection of tabular formats for data summary.

There will be a selection of statistical models to use with the data.

## Actionable Utility

The user will be able to identify possible interventions that could be implemented to
improve public health through modification of government policy.  This will be
targeted to the selected country.



